# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - test-aeg

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Create packages directory
        run: New-Item -ItemType Directory -Force -Path .\packages

      - name: Restore NuGet packages
        shell: pwsh
        run: nuget restore DemoWebApp.csproj -PackagesDirectory .\packages

      - name: List contents of the packages folder
        shell: pwsh
        run: Get-ChildItem -Path .\packages -Recurse

      - name: Install .NET Framework 4.5
        run: |
          $url = "https://download.microsoft.com/download/E/A/1/EA19D08A-22E9-495C-8F35-D44B8A1C259E/NDP45-DevPack-KB2901907.exe"
          $output = "dotNetFx45Devpack.exe"
          Invoke-WebRequest -Uri $url -OutFile $output
          Start-Process -FilePath $output -ArgumentList '/quiet /norestart' -Wait

      - name: Publish to folder
        run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:RestorePackagesPath=".\packages" /p:_PackageTempDir="\published\" /p:TargetFrameworkVersion=v4.5

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: ASP-app
          path: '/published/**'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ASP-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'test-aeg'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_24430394BCB54E2FBE8F7A5F2C84C0E3 }}
